name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  codex_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codex Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          PR_URL: ${{ github.event.pull_request.url }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python3 codex_review.py
